{ "global": {
    "GNSS_SEARCH_RATE": 2, # rate that we get GNSS readings in seconds, minimum 1
    "GNSS_SEND_BATCH_SIZE": 5 # number of GNSS readings to send in one batch
  },
  "mode": "lora", # Options: "lora", "cellular", "dual"
  "gnss_hz": 0.5,
  "serial_port": "/dev/ttyUSB0",
  "serial_baud": 9600,
  "rfid_enabled": true,
  "uplink": {
    "lora": {
      "frequency_mhz": 868.0,
      "spreading_factor": 7
    },
    "cellular": {
      "apn": "internet",
      "endpoint": "https://example.com/ingest"
    }
  },
  "logging": {
    "level": "INFO",
    "file": "logs/runtime.log"
  }
}
